### ISSUE TITLE
StartShow Improvment

### ISSUE THREAD

**Issue by mokabyls** [MichaelGreenNZ/MA3_StartShow#5]
Hi @MichaelGreenNZ,

I've developed a plugin based on your color preset idea but with a Lua implementation to avoid duplicating variables across color sequences. Here's how it works:

1. It detects active "Color Group *" sequences
2. Allows users to select a target macro
3. Stores all active sequences in the selected macro
4. Provides user feedback and error handling

The plugin is designed to help users store active Color Group sequences into a macro for easy recall. It includes features like:

- Automatic detection of active sequences
- User-friendly macro selection
- Error handling and user feedback
- Cleanup of orphan temporary macros

I'd be happy to include this in the show if you're interested. Thank you for sharing your ideas and inspiring this plugin!

```lua
-- Plugin: Store active "Color Group *" sequences into a macro
-- Purpose: This plugin helps users store active Color Group sequences into a macro for easy recall.
-- Features:
-- - Detects active Color Group sequences
-- - Allows user to select a target macro
-- - Stores all active sequences in the selected macro
-- - Provides user feedback and error handling
-- Based on skeleton-grandma3-plugin.lua

local pluginName    = select(1, ...)
local componentName = select(2, ...)
local signalTable   = select(3, ...)
local pluginHandle  = select(4, ...)

-- ****************************************************************
-- Main function
-- ****************************************************************
local function Main(displayHandle, argument)
    local mkbma_selected_macro = 'mkbma_selected_macro'
    
    -- 0. Cleanup
    DelVar(UserVars(), mkbma_selected_macro)

    -- 1. Search for all "Color Group *" sequences
    local seqList = ObjectList('Sequence "Color Group *"')

    -- 2. Filter active sequences
    local activeSeqs = {}
    if seqList and #seqList > 0 then
        for _, seq in ipairs(seqList) do
            if seq:HasActivePlayback() then
                table.insert(activeSeqs, seq)
            end
        end
    end

    -- 3. If no active sequence is found
    if #activeSeqs == 0 then
        -- Display in the console
        Echo("ℹ️ No active \"Color Group *\" sequence found.")

        -- Display a simple popup with an "OK" button
        local msg = {
            title    = "No Active Sequence",
            message  = 'No active \"Color Group *\" sequence found at the moment.',
            commands = { {value = 1, name = "OK"} },
        }
        MessageBox(msg)
        return
    end

    -- 4. Prepare user variable to store selected macro
    

    -- 5. 🧹 Cleanup orphan temporary macros
    local macros = DataPool().Macros:Children()
    for _, macro in ipairs(macros) do
        local lines = macro:Children()
        local firstLine = lines and lines[1] or nil
        if firstLine and firstLine.Command and firstLine.Command:find(mkbma_selected_macro) then
            macro:Remove(macro:Index())
        end
    end

    -- 6. 🔧 Create temporary macro to capture user click
    local temp_macro = DataPool().Macros:Acquire()
    local macro_line = temp_macro:Acquire()
    macro_line:Set('command', string.format('SetUserVariable "%s" "', mkbma_selected_macro))
    macro_line:Set('execute', false)  -- <-- On ajoute cette ligne pour ne pas exécuter immédiatement

    -- User instructions
    Printf("🖱️ Click on the macro where you want to store the active sequences.")
    Printf("⏳ Waiting for selection...")

    -- Start temporary macro execution
    Cmd("Go Macro " .. temp_macro:Index())

    -- 7. ⏳ Wait for user click with timeout to avoid infinite loop
    local timeout     = 10
    local elapsedTime = 0
    local step        = 0.1
    while not GetVar(UserVars(), mkbma_selected_macro) and elapsedTime < timeout do
        coroutine.yield(step)
        elapsedTime = elapsedTime + step
    end

    -- If timeout exceeded
    if not GetVar(UserVars(), mkbma_selected_macro) then
        Echo("❌ Macro selection canceled (timeout).")
        MessageBox{
            title    = "Selection canceled",
            message  = "No macro was selected (timeout).",
            commands = { {value = 1, name = "OK"} },
        }
        temp_macro:Remove(temp_macro:Index())
        CmdIndirectWait("")
        return
    end

    -- 8. Retrieve selected macro handle
    local selected_str = GetVar(UserVars(), mkbma_selected_macro)

    selected_str = string.gsub(selected_str, "^%s*(.-)%s*$", "%1") -- trim

    -- 🧹 Final cleanup
    temp_macro:Remove(temp_macro:Index())
    DelVar(UserVars(), mkbma_selected_macro)

    if selected_str == "" then
        ErrPrintf("❌ No object selected.")
        return
    end

    local selected_obj = nil
    local id = selected_str:match("^Macro%s+(%d+)$")

    if id then
        selected_obj = ObjectList(string.format("Macro %d", id))[1]
        if not selected_obj then
            Echo(string.format("✔ Macro \"%s\" created as it didn't exist.", tostring(id)))
            CmdIndirectWait(string.format('Store Macro %d.1 /o', id))
            selected_obj = ObjectList(string.format("Macro %d", id))[1]
            if not selected_obj then
                ErrPrintf("❌ Aucune Macro avec l'ID %d trouvé.", tonumber(id))
                return
            end
        end
    else
        selected_obj = ObjectList(string.format('Macro "%s"', selected_str))[1]
    end

    -- 9. Check that the clicked object is a Macro
    if not selected_obj or selected_obj:GetClass() ~= "Macro" then
        Echo("❌ The selected object is not a valid macro.")
        MessageBox{
            title    = "Selection error",
            message  = "The selected object is not a macro. Please try again.",
            commands = { {value = 1, name = "OK"} },
        }
        return
    end

    -- 10. The current name of the macro is retrieved for proposal in the TextInput.
    local current_name = selected_obj.Name or ""

    -- 11. Popup to request new macro name
    local prompt_title   = "New macro name"
    local prompt_message = "Enter the new name for the selected macro:"
    local new_name = TextInput(
        prompt_title,
        current_name,
        nil,
        nil
    )
    if not new_name or new_name == "" then
        new_name = current_name
    end

    -- 12. Remove all existing lines from the selected macro
    local lines = selected_obj:Children()
    for _, line in ipairs(lines) do
        line:Remove(line:Index())
    end

    -- 13. Change macro name
    selected_obj:Set('Name', new_name)

    -- 14. Insert "Go+ Sequence \"<SequenceName>\"" line for each active sequence
    for _, seq in ipairs(activeSeqs) do
        local seq_name = seq.Name or ("#" .. tostring(seq.No))
        local new_line = selected_obj:Acquire()
        new_line:Set('command', string.format('Go+ Sequence "%s"', seq_name))
    end

    -- 15. Final feedback
    Echo(string.format("✔ Macro \"%s\" updated with %d active sequence(s).", new_name, #activeSeqs))
end

-- ****************************************************************
-- Cleanup function (nothing special here)
-- ****************************************************************
local function Cleanup()
end

-- ****************************************************************
-- Not used here
-- ****************************************************************
local function Execute(Type, ...)
end

-- ****************************************************************
-- Export des entry points
-- ****************************************************************
return Main, Cleanup, Execute

```

Best regards,

Billy

**Comment by MichaelGreenNZ** [comment]
@mokabyls This is amazing! I would love to include it in the next version! i'm away for work for awhile, but attempting to redo a bunch of things using the new tags function. Hope to have something ready in about a month!

Just so I don't make any mistakes, with this, I can remove the SetUserVar commands in the Color Group Sequences?

**Comment by mokabyls** [comment]
Hello @MichaelGreenNZ ,

are you talking about the variables you define in your sequences? If so, no problem.

In fact, the plugin will search for all sequences named “Color Group *” (step 1) and look for those that are active.

For my part, I create a variable to do the same as you do, enabling selection of the macro where to save the Go+.

And for your store button, you just have to put: Call Plugin "Plugin name".

In a second phase, we could perhaps even improve the showfile and plugin by allowing active sequences for positions or gobos to be saved. that would be conceivable.

**Comment by MichaelGreenNZ** [comment]
> Hello @MichaelGreenNZ ,
> 
> are you talking about the variables you define in your sequences? If so, no problem.
> 
> In fact, the plugin will search for all sequences named “Color Group *” (step 1) and look for those that are active.
> 
> For my part, I create a variable to do the same as you do, enabling selection of the macro where to save the Go+.
> 
> And for your store button, you just have to put: Call Plugin "Plugin name".
> 
> In a second phase, we could perhaps even improve the showfile and plugin by allowing active sequences for positions or gobos to be saved. that would be conceivable.
> 

Amazing. I'll have a play around, and can definitely see this working great for gobo and position. Although an even better one would be for the phasers layouts, so you could save a setting you like and quickly recall that phaser setup.

**Comment by MichaelGreenNZ** [comment]
@mokabyls Hi Billy

Sorry it's taken me so long to look at this, Been away on tour and not able to look at showfile.

I've just tried to load into ma3, but it's showing up with a syntax error. Seems to be something around line 149 

`local new_name = TextInput(`

**Comment by mokabyls** [comment]
Hi @MichaelGreenNZ ,

Sorry, I forgot a comma, which made the code unusable. It has been corrected in my previous message.

**Comment by MichaelGreenNZ** [comment]
Hey @mokabyls,

thanks for the quick reply!

hmm, still not working, now saying `LUA: no reference to main function found for plugin Store Color Picker Preset`

**Comment by MichaelGreenNZ** [comment]
@mokabyls 

Huh, there you go, showfile reload, and it works! thanks so much! I'll let you know when it's live!

**Comment by MichaelGreenNZ** [comment]
@mokabyls 

So...... I made some tweaks to the plugin, with the help of chat GPT.
Thank you for the inspiration. It now opens a UI that lets you select the Macro Pool to store in and Rename it.

```LUA
-- Based on the Plugin built by Billy @mokabyls on github - https://github.com/mokabyls
-- Plugin: Store active "Color Group *" sequences into a chosen Macro via custom 5×4 UI
-- Single overlay: 5x4 grid -> inline confirm+rename (no MessageBox/TextInput races)
-- Auto keyboard: try LineEdit:StartEdit(); fallback to TextInput(caller=display)
-- grandMA3 v2.2


local pluginName    = select(1, ...)
local componentName = select(2, ...)
local signalTable   = select(3, ...)
local pluginHandle  = select(4, ...)

-- ---------- helpers ----------
local function quote_name(s)
  s = tostring(s or "")
  s = s:gsub('"', '\\"')
  return '"' .. s .. '"'
end

local function get_display()
  local idx = Obj.Index(GetFocusDisplay())
  if idx > 5 then idx = 1 end
  return GetDisplayByIndex(idx)
end

local function CreateUI(class, parent, params, onDelete)
  if params and not params.focus and class ~= "LineEdit" then params.focus = "Never" end
  local element = parent:Append(class)
  if params then
    for k, v in pairs(params) do element[k] = v end
  end
  if onDelete then element:HookDelete(onDelete) end
  return element
end

local function getOrCreateMacroById(id)
  local obj = ObjectList(("Macro %d"):format(id))[1]
  if not obj then
    Cmd(("Store Macro %d.1 /o"):format(id))
    obj = ObjectList(("Macro %d"):format(id))[1]
  end
  return obj
end

-- Build overlay with a 5×4 grid (5401–5420) that swaps to inline confirm+rename
local function overlay_grid_with_inline_confirm(activeSeqs)
  local ui = {}
  local display = get_display()
  local closed = false

  local function close_window()
    if ui.base and ui.base.Parent then ui.base:Parent():Delete(ui.base.index) end
    ui.base = nil
  end

  -- Base window (no auto-close / no escape-close to avoid races)
  ui.base = CreateUI("BaseInput", display.ScreenOverlay, {
    W = "900", H = "560", Rows = 2, Columns = 1,
    CloseOnEscape = "No",
    AutoClose     = "No",
    MinSize       = "720,420", MaxSize = "1400,900",
  }, function() closed = true end)

  -- Title bar
  ui.titleBar = CreateUI("TitleBar", ui.base, { Anchors = "0,0", Rows = 1, Columns = 2, Texture = "corner2" })
  ui.titleBar[2][2].SizePolicy = "Fixed"; ui.titleBar[2][2].Size = "50"
  CreateUI("TitleButton", ui.titleBar, {
    Anchors = "0,0", Texture = "corner1", Text = "Select Macro Slot (5401–5420)", Icon = "object_plugin1"
  })
  CreateUI("CloseButton", ui.titleBar, { Anchors = "1,0", Texture = "corner2" })

  -- Dialog frame (both views are children of this, matching your working version)
  ui.dialog = CreateUI("DialogFrame", ui.base, { Anchors = "0,1", Columns = 1, Rows = 2, name = "dlg" })
  ui.dialog[1][2].SizePolicy = "Fixed"; ui.dialog[1][2].Size = "60"
  ui.dialog:WaitInit()

  -- GRID: 5 columns × 4 rows (same parent & anchors as your working code)
  ui.grid = CreateUI("UILayoutGrid", ui.dialog, {
    Anchors = "0,0",
    Columns = 5, Rows = 4, DefaultMargin = "8", Margin = "16,16,16,8",
  })
  ui.grid:WaitInit()

  -- Footer with Cancel (optional, matches your working structure)
  ui.footer = CreateUI("UILayoutGrid", ui.dialog, { Anchors = "0,1", Columns = 3, Rows = 1 })
  ui.footer[2][1].SizePolicy = "Fixed"; ui.footer[2][1].Size = "120"
  ui.footer[2][3].SizePolicy = "Fixed"; ui.footer[2][3].Size = "120"
  ui.cancel = CreateUI("Button", ui.footer, {
    Anchors = "1,0", Text = "Cancel", Texture = "corner15",
    PluginComponent = pluginHandle, Clicked = "InlineCancel",
  })
  signalTable["InlineCancel"] = function() close_window() end

  -- CONFIRM PANEL (hidden initially)
  ui.confirm = CreateUI("UILayoutGrid", ui.dialog, {
    Anchors = "0,0",
    Columns = 1, Rows = 4, DefaultMargin = "8", Margin = "16,16,16,8",
    Visible = "No",
  })
  ui.confirm:WaitInit()

  local function show_grid()
    ui.confirm.Visible = "No"
    ui.grid.Visible = "Yes"
  end
  local function show_confirm()
    ui.grid.Visible = "No"
    ui.confirm.Visible = "Yes"
  end

  -- Confirm panel contents
  ui.info = CreateUI("UIObject", ui.confirm, {
    Anchors = "0,0",
    Text = "",
    TextAlignmentV = "Center",
    ContentDriven = "Yes",
    ContentWidth = "No",
    TextAutoAdjust = "Yes",
    Interactive = "No",
  })

  ui.renameRow = CreateUI("UILayoutGrid", ui.confirm, { Anchors = "0,1", Columns = 3, Rows = 1 })
  ui.renameRow[2][1].SizePolicy = "Fixed"; ui.renameRow[2][1].Size = "160"
  CreateUI("UIObject", ui.renameRow, {
    Anchors = "0,0", Text = "New Macro Name:", TextalignmentH = "Left", HasHover = "No",
  })

  -- Rename field — editable + with on-screen keyboard button
  ui.rename = CreateUI("LineEdit", ui.renameRow, {
    Anchors = "1,0,2,0",
    Content = "",
    ReadOnly = "No",
    ShowKeyboardButton = "Yes",
    VkPluginName = "TextInput",   -- your working VK plugin
  })

  CreateUI("UIObject", ui.confirm, { Anchors = "0,2", Text = "", HasHover = "No", Interactive = "No" })

  -- Button row — Back (left, smaller) and Store (center, bigger)
  ui.btnRow = CreateUI("UILayoutGrid", ui.confirm, { Anchors = "0,3", Columns = 3, Rows = 1 })
  -- Make left smaller, center bigger, right flexible
  ui.btnRow[2][1].SizePolicy = "Fixed"; ui.btnRow[2][1].Size = "150"  -- Back (smaller)
  ui.btnRow[2][2].SizePolicy = "Fixed"; ui.btnRow[2][2].Size = "240"  -- Store (bigger)
  -- (no fixed width for column 3; leave it flexible as spacer)

  ui.backBtn = CreateUI("Button", ui.btnRow, {
    Anchors = "1,0", Text = "Back", Texture = "corner12",
    PluginComponent = pluginHandle, Clicked = "InlineBack",
  })
  ui.applyBtn = CreateUI("Button", ui.btnRow, {
    Anchors = "2,0", Text = "Store", Texture = "corner15",  -- renamed & centered
    PluginComponent = pluginHandle, Clicked = "InlineApply",
  })

  signalTable["InlineBack"] = function() show_grid() end

  -- Create the 20 grid buttons (same anchors pattern you had working)
  local col, row = 0, 0
  for slot = 5401, 5420 do
    local sig = "SlotChoose_" .. slot
    local btn = CreateUI("Button", ui.grid, {
      Anchors = ("%d,%d"):format(col, row),
      Text = tostring(slot), Texture = "corner5",
      PluginComponent = pluginHandle, Clicked = sig,
    })
    btn.W = "150"; btn.H = "90"; btn.AlignmentH = "Center"; btn.AlignmentV = "Center"

    signalTable[sig] = function()
      -- Prepare confirm view for this slot (inline)
      local macro = getOrCreateMacroById(slot); if not macro then ErrPrintf(" Macro %d unavailable.", slot) return end
      local existing = macro:Children() or {}
      local mname = macro.Name or ""

      ui.info.Text = ("Macro %d%s currently has %d line(s).\nReplace its contents with %d active sequence(s)?")
                      :format(slot, mname ~= "" and (" ("..mname..")") or "", #existing, #activeSeqs)
      ui.rename.Content = mname or ""

      -- Bind STORE for this selected slot/macro
      signalTable["InlineApply"] = function()
        local new_name = ui.rename.content or ui.rename.Content or ""
        if new_name ~= "" and new_name ~= mname then
          macro:Set("Name", new_name)
        end
        -- Clear and write (always replace)
        Cmd(("Delete Macro %d.* /nc /q"):format(slot))
        for _, s in ipairs(activeSeqs) do
          local seq_name = s.Name or ("#" .. tostring(s.No or ""))
          local line = macro:Acquire()
          line:Set("Command", ("Go+ Sequence %s"):format(quote_name(seq_name)))
        end
        Echo((" Macro %supdated with %d active sequence(s) at slot %d.")
              :format(((macro.Name or "") ~= "" and (macro.Name .. " ") or ""), #activeSeqs, slot))
        close_window()
      end

      -- Show confirm and try inline editing; fallback to TextInput if StartEdit isn't available
      show_confirm()
      coroutine.yield({ui = 1})                 -- settle UI
      if ui.rename then
        ui.rename.Focus = "Always"              -- ensure it can take focus
        if ui.rename.StartEdit then
          ui.rename:StartEdit()                 -- auto-launch VK on builds that support it
        else
          coroutine.yield(0.25)                 -- small guard so overlay is stable
          local current = ui.rename.content or ui.rename.Content or ""
          local typed = TextInput("New Macro Name", current, nil, { caller = display })
          if typed and typed ~= "" then
            ui.rename.Content = typed           -- reflect TextInput result back in the field
          end
        end
      end
    end

    col = col + 1
    if col >= 5 then col = 0; row = row + 1 end
  end

  -- Start on grid, keep overlay alive until user acts or closes it
  show_grid()
  while not closed and ui.base do
    coroutine.yield({ui = 1})
  end
end

local function Main(displayHandle, argument)
  -- Gather active "Color Group *" sequences
  local seqList = ObjectList('Sequence "Color Group *"')
  local active = {}
  if seqList then
    for _, s in ipairs(seqList) do
      if type(s.HasActivePlayback) == "function" and s:HasActivePlayback() then
        table.insert(active, s)
      end
    end
  end
  if #active == 0 then
    Echo(' No active "Color Group *" sequence found.')
    return
  end

  -- Quick path: allow direct call with a slot argument (no UI)
  local argnum = tonumber(argument)
  if argnum and argnum >= 5401 and argnum <= 5420 then
    local macro = getOrCreateMacroById(argnum); if not macro then ErrPrintf(" Macro %d unavailable.", argnum) return end
    Cmd(("Delete Macro %d.* /nc /q"):format(argnum))
    for _, s in ipairs(active) do
      local seq_name = s.Name or ("#" .. tostring(s.No or ""))
      local line = macro:Acquire()
      line:Set("Command", ("Go+ Sequence %s"):format(quote_name(seq_name)))
    end
    Echo((" Macro %supdated with %d active sequence(s) at slot %d.")
          :format(((macro.Name or "") ~= "" and (macro.Name .. " ") or ""), #active, argnum))
    return
  end

  -- Otherwise, show the single-overlay UI (grid -> inline confirm+rename)
  overlay_grid_with_inline_confirm(active)
end

local function Cleanup() end
local function Execute(Type, ...) end
return Main, Cleanup, Execute
